### ISSUE TITLE
Align padding on 'Active Pots' cards

### ISSUE THREAD

**Issue by dieterdesign** [moonpotdev/moonpot-app#69]
<img width="598" alt="Screenshot 2021-07-27 at 15 11 05" src="https://user-images.githubusercontent.com/87697610/127169037-fa1600e0-ffde-4006-b784-caadbefc1dbf.png">

**Comment by Tumble17** [comment]
This relates directly to home.js. There are currently cards in home.js, vault.js and dashboard.js.
